export const WORDS = [
  "orbit",
  "laser",
  "nova",
  "probe",
  "ion",
  "flare",
  "drone",
  "asteroid",
  "cosmic",
  "quasar",
  "alien",
  "cargo",
  "gamma",
  "plasma",
  "nebula",
  "quantum",
  "signal",
  "vector",
  "thruster",
  "sector",
  "comet",
  "docking",
  "module",
  "saturn",
  "apollo",
  "zenith",
  "delta",
  "omega",
  "pilot",
  "lunar",
  "titan",
  "terra",
  "hyper",
  "warp",
  "atlas",
  "array",
  "horizon",
  "relay",
  "galaxy",
  "sphere",
  "nexus",
  "vortex",
  "cosmos",
  "photon",
  "blaster",
  "drift",
  "boost",
  "phase",
  "ionize",
  "gauge",
  "synth",
  "frame",
  "spend",
  "ditto",
  "goes",
  "yet",
]

// We derive simple pools by word length; the game also enforces min/max length per phase.
export const wordsEasy = WORDS.filter((w) => w.length <= 5)
export const wordsMedium = WORDS.filter((w) => w.length >= 5 && w.length <= 7)
export const wordsHard = WORDS.filter((w) => w.length >= 7)
